# Generated by Django 5.1.6 on 2025-02-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
